name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag helloworld-test
    - name: Push To Registry
      # You may pin to the exact commit or the version.
      # uses: redhat-actions/push-to-registry@df878026e36864aa6bf9a5b7afe63637cb88ef8c
      uses: redhat-actions/push-to-registry@v2.6
      with:
        tags: helloworld-test
        registry: ccr.ccs.tencentyun.com/fflow/fflow
        username: 100016873402
        password: ${{ secrets.REGISTRY_PWD }}
